apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-ui.fullname" . }}
  labels:
    {{- include "product-ui.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "product-ui.selectorLabels" . | nindent 4 }}
